# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'multiqml_ui_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MultiQmlForm(object):
    def setupUi(self, MultiQmlForm):
        MultiQmlForm.setObjectName("MultiQmlForm")
        MultiQmlForm.resize(278, 206)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            MultiQmlForm.sizePolicy().hasHeightForWidth()
        )
        MultiQmlForm.setSizePolicy(sizePolicy)
        MultiQmlForm.setLocale(
            QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates)
        )
        MultiQmlForm.setSizeGripEnabled(False)
        MultiQmlForm.setModal(False)
        self.gridLayout = QtWidgets.QGridLayout(MultiQmlForm)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(MultiQmlForm)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label.sizePolicy().hasHeightForWidth()
        )
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.rbnRasterLayers = QtWidgets.QRadioButton(MultiQmlForm)
        self.rbnRasterLayers.setCheckable(True)
        self.rbnRasterLayers.setChecked(False)
        self.rbnRasterLayers.setObjectName("rbnRasterLayers")
        self.gridLayout.addWidget(self.rbnRasterLayers, 0, 1, 1, 1)
        self.rbnVectorLayers = QtWidgets.QRadioButton(MultiQmlForm)
        self.rbnVectorLayers.setObjectName("rbnVectorLayers")
        self.gridLayout.addWidget(self.rbnVectorLayers, 0, 2, 1, 1)
        self.lvMapLayers = QtWidgets.QListView(MultiQmlForm)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.lvMapLayers.sizePolicy().hasHeightForWidth()
        )
        self.lvMapLayers.setSizePolicy(sizePolicy)
        self.lvMapLayers.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lvMapLayers.setSelectionMode(
            QtWidgets.QAbstractItemView.ExtendedSelection
        )
        self.lvMapLayers.setObjectName("lvMapLayers")
        self.gridLayout.addWidget(self.lvMapLayers, 1, 0, 2, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pbnApplyStyle = QtWidgets.QPushButton(MultiQmlForm)
        self.pbnApplyStyle.setObjectName("pbnApplyStyle")
        self.verticalLayout.addWidget(self.pbnApplyStyle)
        self.pbnRestoreDefaultStyle = QtWidgets.QPushButton(MultiQmlForm)
        self.pbnRestoreDefaultStyle.setObjectName("pbnRestoreDefaultStyle")
        self.verticalLayout.addWidget(self.pbnRestoreDefaultStyle)
        self.pbnSelectAllLayers = QtWidgets.QPushButton(MultiQmlForm)
        self.pbnSelectAllLayers.setObjectName("pbnSelectAllLayers")
        self.verticalLayout.addWidget(self.pbnSelectAllLayers)
        self.pbnClose = QtWidgets.QPushButton(MultiQmlForm)
        self.pbnClose.setObjectName("pbnClose")
        self.verticalLayout.addWidget(self.pbnClose)
        self.gridLayout.addLayout(self.verticalLayout, 2, 1, 1, 2)
        self.checkMakeDefault = QtWidgets.QCheckBox(MultiQmlForm)
        self.checkMakeDefault.setObjectName("checkMakeDefault")
        self.gridLayout.addWidget(self.checkMakeDefault, 1, 1, 1, 2)
        self.label.setBuddy(self.lvMapLayers)

        self.retranslateUi(MultiQmlForm)
        QtCore.QMetaObject.connectSlotsByName(MultiQmlForm)
        MultiQmlForm.setTabOrder(self.pbnApplyStyle, self.lvMapLayers)
        MultiQmlForm.setTabOrder(self.lvMapLayers, self.pbnRestoreDefaultStyle)
        MultiQmlForm.setTabOrder(
            self.pbnRestoreDefaultStyle, self.pbnSelectAllLayers
        )
        MultiQmlForm.setTabOrder(self.pbnSelectAllLayers, self.rbnRasterLayers)
        MultiQmlForm.setTabOrder(self.rbnRasterLayers, self.rbnVectorLayers)
        MultiQmlForm.setTabOrder(self.rbnVectorLayers, self.pbnClose)

    def retranslateUi(self, MultiQmlForm):
        _translate = QtCore.QCoreApplication.translate
        MultiQmlForm.setWindowTitle(_translate("MultiQmlForm", "Assign style"))
        self.label.setText(_translate("MultiQmlForm", "Layers:"))
        self.rbnRasterLayers.setText(_translate("MultiQmlForm", "Raster"))
        self.rbnVectorLayers.setText(_translate("MultiQmlForm", "Vector"))
        self.pbnApplyStyle.setText(
            _translate("MultiQmlForm", "Apply style ...")
        )
        self.pbnRestoreDefaultStyle.setText(
            _translate("MultiQmlForm", "Restore initial style")
        )
        self.pbnSelectAllLayers.setText(
            _translate("MultiQmlForm", "Select all layers")
        )
        self.pbnClose.setText(_translate("MultiQmlForm", "Close"))
        self.checkMakeDefault.setText(
            _translate("MultiQmlForm", "Save as default")
        )


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MultiQmlForm = QtWidgets.QDialog()
    ui = Ui_MultiQmlForm()
    ui.setupUi(MultiQmlForm)
    MultiQmlForm.show()
    sys.exit(app.exec_())
